countries = ['India', 'America', 'Tokyo', 'Beijing', 'Nepal', 'Brazil', 'Australia', 'Congo']
print(f'these are the set of contries that i want to visit: {countries}')
countries[1] = 'U.S.A'
print(countries)
countries.append('North korea')
print(countries)
countries.insert(1, 'Russia')
print(countries)
del countries[4]
print(countries)
popped_country = countries.pop()
print(countries)
countries.pop(0)
print(countries)
countries.remove('Nepal')
print(countries)
print(f'\n{sorted(countries)}')
print(countries)
print(f'\n{sorted(countries, reverse=True)}')
print(countries)
countries.sort()
print(countries)
countries.sort(reverse=True)
print(countries)
countries.reverse()
print(f'\n{countries}')
print(f'\n{len(countries)}')
