invitees = ['jayakar', 'rudheer', 'varshith', 'vikash']
message = 'I am Pavan teja, I invite you this party'
print(f'Hii ra {invitees[0].title()} {message}')
print(f'Hii ra {invitees[1].title()} {message}')
print(f'Hii ra {invitees[2].title()} {message}')
print(f'Hii ra {invitees[3].title()} {message}')
print(f'\noh! {invitees[3].title()} could not make it to this party as it is lockdown and he is far away in bihar')
invitees[3] = 'advaith'
print('\nso now the new invitations would be like: ')
print(f'\tHii ra {invitees[0].title()} {message}')
print(f'\tHii ra {invitees[1].title()} {message}')
print(f'\tHii ra {invitees[2].title()} {message}')
print(f'\tHii ra {invitees[3].title()} {message}')
print(f'\nWow! it is amazing I have found a bigger dining table, so now I can now call more people to this party.....')
invitees.insert(0, 'dheeraj')
invitees.insert(2, 'charan sai')
invitees.append('harshil')
print('so now the new invitations would be like: ')
print(f'\t\tHii ra {invitees[0].title()} {message}')
print(f'\t\tHii ra {invitees[1].title()} {message}')
print(f'\t\tHii ra {invitees[2].title()} {message}')
print(f'\t\tHii ra {invitees[3].title()} {message}')
print(f'\t\tHii ra {invitees[4].title()} {message}')
print(f'\t\tHii ra {invitees[5].title()} {message}')
print(f'\t\tHii ra {invitees[6].title()} {message}')