places = ['london', 'moon', 'america', 'paris', 'vegas']
print(f'\noriginal list of places: {places}')
print(f'\nsorted list of places are: {sorted(places)}')
print(f'\nagain see the original list it is same it doesnot change: {places}')
print(f'\nreverse of sorted list is: {sorted(places, reverse=True)}')
print(f'\nonce agan see original list is same: {places}')
places.reverse()
print(f'\nsee when reverse is applied the order of original list also changes: {places}')
places.reverse()
print(f'\nsee when reverse is applied double times the original list remains same as it is reversed double times: {places}')
places.sort()
print(f'\nsee when sort is applied the original order of list also changes in alphabetical order: {places}')
places.sort(reverse=True)
print(f'\nsee when sort(reverse=True) is applied it again changesthe list in reverse alphabetical order: {places}')
print('\nthis is how you have to use sort, reverse methods and sorted function')